---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: ["--allow-multiple-documents", "--unsafe"]
    exclude: ^helm/charts
  - id: check-added-large-files
    args: ['--maxkb=1024']

- repo: https://github.com/adrienverge/yamllint
  rev: v1.32.0
  hooks:
  - id: yamllint

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.22
  hooks:
  - id: markdown-link-check
    exclude: apps/react-demo/README.md
