trigger: none
pr: none

resources:
  repositories:
  # Repository with CI templates
  - repository: templates
    type: github
    name: artazar/azure-pipeline-templates
    endpoint: github
    ref: ${{ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') }}

extends:
  template: azure-pipelines/pipelines/java.yaml@templates
  parameters:
    baseImage: tomcat
    appGroup: test
    projectSubdirectory: ./apps/spring-boot-demo
    containerImageName: spring-boot-demo
